name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    #
    # Set up Python
    #

    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    #
    # Install Python dependencies
    #

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    #
    # Set up environmental settings
    #

    - name: Set PYTHONPATH
      run: |
        export PYTHONPATH=$PWD
        echo $PYTHONPATH

    #
    # Lint
    #

    - name: Lint Python code with flake8
      run: |
        flake8 `find . -name "*.py"`

    #
    # Run tests
    #

    - name: Run unit tests
      run: |
        coverage run --source rabbitmq_client -m unittest \
          tests.test_connection \
          tests.test_consumer
        coverage report -m
    # TODO: Enforce coverage does not drop.
    # TODO: Add integration tests
