name: Test

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672

    steps:
    - uses: actions/checkout@v2

    #
    # Set up Python
    #

    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    #
    # Install Python dependencies
    #

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    #
    # Set up environmental settings
    #

    - name: Set PYTHONPATH
      run: |
        export PYTHONPATH=$PWD
        echo $PYTHONPATH

    #
    # Run tests
    #

    - name: Run unit tests
      run: |
        python -m unittest tests.test_integration.test_consume_from_queue -f -v
